type RainbowProject = { id: number; name: string; description: string; created_at: string }
type RainbowTask = { id: number; project_id: number; title: string; schedule: string; status: string; enabled: number; created_at: string; last_run_at: string | null; next_run_at: string | null }
type RainbowRun = { id: number; task_id: number; task_title: string; status: string; output: string | null; error: string | null; started_at: string; finished_at: string | null }
type ModelConfigInput = { provider: string; base_url: string; api_protocol: 'responses' | 'chat_completions' | 'claude_messages'; text_model: string; image_model: string; video_model: string; voice_model: string; asr_model: string; default_model: string; temperature: number; max_tokens: number; timeout_seconds: number; retry_count: number }
type ModelConfig = ModelConfigInput & { updated_at?: string; has_api_key: boolean }
type RainbowConversation = { id: number; title: string; provider: string; model: string; created_at: string; updated_at: string }
type RainbowMessage = { id: number; conversation_id: number; role: 'user' | 'assistant'; content: string; status: string; error: string | null; created_at: string }
type TextProviderConfig = { provider: string; model: string; configured: boolean; base_url: string }
type ChatEvent = { requestId: string; messageId: number; delta?: string; content?: string; status?: string; error?: string }
type AgentPermissionMode = 'ask' | 'smart' | 'full'
type AgentApprovalDecision = 'allow_once' | 'allow_session' | 'deny'
type AgentStep = { id: number; run_id: number; tool_call_id: string; tool_name: string; label: string; risk: 'read' | 'write' | 'system'; status: 'running' | 'completed' | 'failed'; input: string; output: string; error: string | null; started_at: string; finished_at: string | null }
type AgentRun = { id: number; request_id: string; conversation_id: number; provider: string; model: string; status: 'running' | 'completed' | 'failed' | 'cancelled'; summary: string; error: string | null; started_at: string; finished_at: string | null; steps: AgentStep[] }
type AgentToolEvent = { requestId: string; runId: number; step: AgentStep }
type AgentApprovalPrompt = { approvalId: string; requestId: string; toolCallId: string; toolName: string; label: string; risk: 'write' | 'system'; reason: string; input: unknown; cwd: string }
type TextWork = { id: number; title: string; content: string; conversation_id: number | null; created_at: string }
type ImageProviderConfig = { provider: string; model: string; configured: boolean; base_url: string }
type VoiceProviderConfig = { provider: string; model: string; configured: boolean; base_url: string }
type VoiceSample = { id: number; name: string; file_path: string; mime_type: string; file_size: number; source_type: 'recording' | 'upload'; authorized: number; created_at: string; updated_at: string; data_url: string; missing: number }
type AsrProviderConfig = { provider: string; model: string; configured: boolean; base_url: string }
type ImageGenerationInput = { prompt: string; style: string; size: string; quality: string; count: number; referencePath?: string }
type ImageWork = { id: number; prompt: string; provider: string; model: string; size: string; quality: string; file_path: string; mime_type: string; revised_prompt: string | null; created_at: string; data_url: string }
type WorkType = 'text' | 'image' | 'video' | 'audio'
type UnifiedWork = { key: string; id: number; type: WorkType; title: string; content: string; prompt: string; provider: string; model: string; size: string; quality: string; file_path: string; mime_type: string; conversation_id: number | null; created_at: string; updated_at: string; favorite: number; tags: string; project_ids: string; missing: number; data_url: string }
type WorksPageInput = { page?: number; pageSize?: number; kind?: 'all' | WorkType; query?: string; provider?: string; model?: string; time?: string; projectId?: number }
type WorksPageResult = { items: UnifiedWork[]; total: number; page: number; pageSize: number; counts: Record<'all' | WorkType, number>; providers: string[]; models: string[]; latest: string }
type RecreatePayload = { type: WorkType; prompt: string; provider: string; size?: string; quality?: string; conversationId?: number | null }
type PublishDraft = { title: string; body: string; topics?: string; projectId?: number | null; workKey?: string }
type PublishAccount = { id: number; platform: string; name: string; handle: string; enabled: number; simulation: number; has_secret: boolean; auth_method: string; auth_browser: string; auth_updated_at: string; created_at: string; updated_at: string }
type PublishAccountInput = { platform: string; name: string; handle: string; simulation: boolean; authMethod?: 'browser'; browser?: 'edge' | 'chrome' }
type PublicationStatus = 'draft' | 'scheduled' | 'publishing' | 'published' | 'failed' | 'cancelled'
type Publication = { id: number; account_id: number; platform: string; account_name: string; project_id: number | null; project_name: string; title: string; body: string; topics: string; status: PublicationStatus; scheduled_at: string | null; published_at: string | null; result_url: string | null; error: string | null; work_keys: string; created_at: string; updated_at: string }
type PublicationInput = { accountIds: number[]; projectId?: number | null; title: string; body: string; topics: string; status: string; scheduledAt?: string | null; workKeys: string[] }
type PublicationUpdateInput = Omit<PublicationInput, 'accountIds'> & { accountId: number }
type PublicationValidation = { valid: boolean; errors: string[]; warnings: string[] }
type VideoProject = { id: number; title: string; mode: string; language: string; target_length: number; draft: string; created_at: string; updated_at: string }
type VideoTranscript = { id: number; source_id: number; engine: string; language: string; content: string; status: string; error: string | null; created_at: string; updated_at: string }
type VideoSource = { id: number; video_project_id: number; source_type: 'url' | 'file' | 'text'; source_value: string; display_name: string; platform: string; status: string; duration: number | null; file_size: number | null; error: string | null; created_at: string; updated_at: string; transcript?: VideoTranscript | null }
type VideoProjectInput = { title: string; mode: string; language: string; targetLength: number; draft: string }
type WhisperStatus = { model: string; modelReady: boolean; engineReady: boolean; ready: boolean; modelPath: string; cliPath: string; expectedBytes: number }
type VideoGeneration = { id: number; video_project_id: number; kind: string; mode: string; content: string; provider: string; model: string; parameters: string; created_at: string }
type VideoCopyInput = { action: 'generate' | 'legal'; mode: 'breakdown' | 'inspiration' | 'original'; source: string; targetLength: number; language: string; subject?: string; product?: string; audience?: string; platform?: string; style?: string; rewriteStrength?: number; provider?: string }
type DigitalHumanInput = { imagePath: string; text: string; ratio: string; resolution: string; duration: number; motion: string; provider?: string; videoModel?: string; projectId?: number; title?: string }
type VideoProviderConfig = { provider: string; models: string[]; model: string; configured: boolean; base_url: string }
type AudioWork = { id: number; title: string; prompt: string; provider: string; model: string; voice: string; speed: number; file_path: string; mime_type: string; video_project_id: number | null; created_at: string; missing: number; dataUrl: string }
type VideoWork = { id: number; title: string; prompt: string; provider: string; model: string; ratio: string; resolution: string; duration: number; file_path: string; mime_type: string; video_project_id: number | null; source_image_path: string; created_at: string; dataUrl: string }
type PolishVideoInput = { sourcePath: string; title?: string; subtitleText?: string; burnSubtitles: boolean; subtitleSize: number; subtitleColor: string; subtitlePosition: 'bottom' | 'center' | 'top'; musicPath?: string; sourceVolume: number; musicVolume: number; ratio: '9:16' | '16:9' | '1:1'; quality: '720p' | '1080p'; trimStart: number; trimEnd: number; projectId?: number }
type PolishVideoResult = DigitalHumanResult & { subtitlePath: string }
type DigitalHumanResult = { taskId: number; id: number; title: string; filePath: string; dataUrl: string; provider: string; model: string; ratio: string; resolution: string; duration: number }
type DigitalHumanTask = { id: number; request_id: string; upstream_task_id: string; video_project_id: number | null; title: string; prompt: string; image_path: string; provider: string; model: string; ratio: string; resolution: string; duration: number; motion: string; status: string; progress: number; message: string; result_url: string; file_path: string; video_work_id: number | null; error: string | null; created_at: string; updated_at: string; dataUrl: string }

interface Window {
  electronAPI: {
    selectVideoFile: () => Promise<string | null>
    storage: { status: () => Promise<{ root: string; customized: boolean; defaultRoot: string }>; choose: () => Promise<{ root: string; customized: boolean; defaultRoot: string } | null> }
    video: {
      projects: { list: () => Promise<VideoProject[]>; create: (title?: string) => Promise<VideoProject>; load: (id: number) => Promise<{ project: VideoProject; sources: VideoSource[]; generations: VideoGeneration[] }>; update: (id: number, input: VideoProjectInput) => Promise<VideoProject> }
      sources: { addUrl: (projectId: number, value: string) => Promise<VideoSource>; addFile: (projectId: number) => Promise<VideoSource | null>; addText: (projectId: number, content: string) => Promise<VideoSource>; delete: (id: number) => Promise<boolean>; transcribe: (id: number, language: string, engine?: 'local' | 'api', provider?: string) => Promise<VideoTranscript>; stop: (id: number) => Promise<boolean>; onProgress: (callback: (payload: { sourceId: number; progress: number; message: string }) => void) => () => void }
      copy: { generate: (requestId: string, projectId: number, input: VideoCopyInput) => Promise<VideoGeneration>; stop: (requestId: string) => Promise<boolean>; delete: (id: number) => Promise<boolean> }
      voice: { providers: () => Promise<VoiceProviderConfig[]>; generate: (requestId: string, input: { text: string; voice: string; speed: number; emotion?: string; provider?: string; projectId?: number; title?: string; cloneSampleId?: number }) => Promise<{ id: number; title: string; filePath: string; dataUrl: string; provider: string; model: string; voice: string; speed: number }>; samples: { list: () => Promise<VoiceSample[]>; upload: (name: string, authorized: boolean) => Promise<VoiceSample | null>; saveRecording: (name: string, bytes: Uint8Array, mimeType: string, authorized: boolean) => Promise<VoiceSample>; rename: (id: number, name: string) => Promise<VoiceSample | null>; delete: (id: number) => Promise<boolean> } }
      digitalHuman: { selectImage: () => Promise<{ path: string; name: string; dataUrl: string } | null>; providers: () => Promise<VideoProviderConfig[]>; list: (projectId?: number) => Promise<DigitalHumanTask[]>; generate: (requestId: string, input: DigitalHumanInput) => Promise<DigitalHumanResult>; resume: (requestId: string, taskId: number) => Promise<DigitalHumanResult>; recover: (requestId: string, upstreamTaskId: string, input: DigitalHumanInput) => Promise<DigitalHumanResult>; stop: (requestId: string) => Promise<boolean>; onProgress: (callback: (payload: { requestId: string; progress: number; message: string }) => void) => () => void }
      personal: { audioWorks: () => Promise<AudioWork[]>; selectVideo: () => Promise<{ path: string; name: string; duration: number | null; fileSize: number; dataUrl: string } | null>; compose: (requestId: string, input: { videoPath: string; audioWorkId: number; projectId?: number; title?: string }) => Promise<DigitalHumanResult>; stop: (requestId: string) => Promise<boolean>; onProgress: (callback: (payload: { requestId: string; progress: number; message: string }) => void) => () => void }
      polish: { videoWorks: () => Promise<VideoWork[]>; selectVideo: () => Promise<{ path: string; name: string; duration: number | null; dataUrl: string } | null>; selectMusic: () => Promise<{ path: string; name: string; dataUrl: string } | null>; render: (requestId: string, input: PolishVideoInput) => Promise<PolishVideoResult>; stop: (requestId: string) => Promise<boolean>; onProgress: (callback: (payload: { requestId: string; progress: number; message: string }) => void) => () => void }
      asr: { providers: () => Promise<AsrProviderConfig[]> }
      whisper: { status: () => Promise<WhisperStatus>; download: () => Promise<WhisperStatus>; installEngine: () => Promise<WhisperStatus>; selectEngine: () => Promise<WhisperStatus>; onProgress: (callback: (payload: { progress: number; received: number; total: number; phase?: 'downloading' | 'extracting' }) => void) => () => void }
    }
    projects: { list: () => Promise<RainbowProject[]>; create: (name: string, description?: string) => Promise<RainbowProject>; update: (id: number, name: string, description?: string) => Promise<RainbowProject>; delete: (id: number) => Promise<boolean> }
    tasks: { list: (projectId: number) => Promise<RainbowTask[]>; create: (projectId: number, title: string, schedule?: string) => Promise<RainbowTask>; update: (id: number, title: string, schedule: string, status: string, enabled?: boolean) => Promise<RainbowTask>; delete: (id: number) => Promise<boolean>; runs: (projectId: number) => Promise<RainbowRun[]>; run: (id: number, title?: string) => Promise<{ status: string; finishedAt: string }>; onUpdated: (callback: (taskId: number) => void) => () => void }
    modelConfig: { get: (provider: string) => Promise<ModelConfig>; save: (config: ModelConfigInput, apiKey?: string) => Promise<ModelConfig>; test: (config: ModelConfigInput, apiKey?: string) => Promise<{ ok: boolean; message: string; models: string[] }> }
    conversations: { list: () => Promise<RainbowConversation[]>; create: (title: string, provider: string, model: string) => Promise<RainbowConversation>; update: (id: number, title: string, provider?: string, model?: string) => Promise<RainbowConversation>; delete: (id: number) => Promise<boolean>; messages: (conversationId: number) => Promise<RainbowMessage[]> }
    chat: { providers: () => Promise<TextProviderConfig[]>; selectAttachments: () => Promise<Array<{ name: string; content: string }>>; start: (requestId: string, conversationId: number, prompt: string, provider: string) => Promise<{ userMessage: RainbowMessage; assistantMessage: RainbowMessage }>; stop: (requestId: string) => Promise<boolean>; onDelta: (callback: (payload: ChatEvent) => void) => () => void; onDone: (callback: (payload: ChatEvent) => void) => () => void; onError: (callback: (payload: ChatEvent) => void) => () => void }
    agent: { runs: (conversationId: number) => Promise<AgentRun[]>; start: (requestId: string, conversationId: number, prompt: string, provider: string, permissionMode: AgentPermissionMode) => Promise<{ userMessage: RainbowMessage; assistantMessage: RainbowMessage; run: AgentRun }>; stop: (requestId: string) => Promise<boolean>; respondApproval: (approvalId: string, decision: AgentApprovalDecision) => Promise<boolean>; onDelta: (callback: (payload: ChatEvent) => void) => () => void; onDone: (callback: (payload: ChatEvent) => void) => () => void; onError: (callback: (payload: ChatEvent) => void) => () => void; onTool: (callback: (payload: AgentToolEvent) => void) => () => void; onApproval: (callback: (payload: AgentApprovalPrompt) => void) => () => void }
    works: { listText: () => Promise<TextWork[]>; saveText: (title: string, content: string, conversationId?: number) => Promise<TextWork>; list: () => Promise<UnifiedWork[]>; page: (input: WorksPageInput) => Promise<WorksPageResult>; byKeys: (keys: string[]) => Promise<UnifiedWork[]>; preview: (type: WorkType, id: number) => Promise<UnifiedWork | null>; update: (type: WorkType, id: number, input: { title: string; favorite: boolean; tags: string }) => Promise<boolean>; delete: (type: WorkType, id: number) => Promise<boolean>; exportText: (id: number, title: string, content: string) => Promise<boolean>; openLocation: (path: string) => Promise<boolean>; downloadFile: (path: string, title: string) => Promise<boolean>; addProject: (type: WorkType, id: number, projectId: number) => Promise<boolean>; createTask: (type: WorkType, id: number, projectId: number, title: string) => Promise<RainbowTask>; backup: () => Promise<string | null> }
    image: { providers: () => Promise<ImageProviderConfig[]>; selectReference: () => Promise<{ path: string; name: string; data_url: string } | null>; generate: (requestId: string, provider: string, input: ImageGenerationInput) => Promise<ImageWork[]>; stop: (requestId: string) => Promise<boolean>; works: () => Promise<ImageWork[]>; download: (id: number) => Promise<boolean> }
    publishing: { accounts: { list: () => Promise<PublishAccount[]>; create: (input: PublishAccountInput) => Promise<PublishAccount>; update: (id: number, input: PublishAccountInput & { enabled: boolean }) => Promise<PublishAccount>; delete: (id: number) => Promise<boolean>; test: (id: number) => Promise<{ ok: boolean; message: string }>; authorizeBrowser: (id: number, browser: 'edge' | 'chrome') => Promise<unknown>; importCookies: (id: number) => Promise<unknown>; clearAuthorization: (id: number) => Promise<unknown>; openLogin: (id: number) => Promise<{ ok: boolean; url: string }> }; list: () => Promise<Publication[]>; create: (input: PublicationInput) => Promise<Publication[]>; update: (id: number, input: PublicationUpdateInput) => Promise<Publication>; validate: (id: number) => Promise<PublicationValidation>; run: (id: number) => Promise<Publication>; cancel: (id: number) => Promise<Publication>; retry: (id: number) => Promise<Publication>; complete: (id: number) => Promise<Publication>; fail: (id: number) => Promise<Publication>; copy: (id: number) => Promise<Publication>; delete: (id: number) => Promise<boolean>; onUpdated: (callback: (id: number) => void) => () => void }
  }
}
